"""
Auto-generated by WebInspector
URL: {url}
Technology: Angular
Generated: {generated_date}

Selectors:
  Card:  {card_selector}  ({card_count} found on inspection)
  Name:  {name_selector}
  Price: {price_selector}
  Link:  {link_selector}

Pagination: {pagination_type}  (param: {pagination_param})
"""
import asyncio
import logging
from playwright.async_api import async_playwright
from src.browsers.playwright_browser import new_context
from src.utils import parse_tr_price

logger = logging.getLogger("bakkal_monitor.parsers.{site_name}")

BASE_URL = "{base_url}"
TARGET_URLS = [{target_urls}]
CARD_SEL   = "{card_selector}"
NAME_SEL   = "{name_selector}"
PRICE_SEL  = "{price_selector}"
LINK_SEL   = "{link_selector}"
LINK_VIA_PARENT = {link_via_parent}
{pagination_const}

async def scrape() -> list[dict]:
    products: list[dict] = []

    async with async_playwright() as p:
        browser, context = await new_context(p)

        for base_url in TARGET_URLS:
            page = await context.new_page()
            try:
                await page.goto(base_url, wait_until="networkidle", timeout=60_000)

                # Angular: wait for component render
                try:
                    await page.wait_for_function(
                        f"() => document.querySelectorAll('{CARD_SEL}').length > 0",
                        timeout=15_000,
                    )
                except Exception:
                    pass
                await asyncio.sleep(3)
{cookie_dismiss_block}
{pagination_loop_start}
                    cards = await page.query_selector_all(CARD_SEL)
                    if not cards:
                        logger.info(f"No cards found — stopping at page {{page_num}}")
                        break

                    for card in cards:
                        try:
                            name_el  = await card.query_selector(NAME_SEL)
                            price_el = await card.query_selector(PRICE_SEL)
                            if not name_el or not price_el:
                                continue
                            name  = (await name_el.inner_text()).strip()
                            price_raw = (await price_el.inner_text()).strip()
                            price = parse_tr_price(price_raw)
{link_extraction_block}
                            products.append({{
                                "product_name":  name,
                                "current_price": price,
                                "market_name":   "{site_name}",
                                "product_url":   href or base_url,
                            }})
                        except Exception as exc:
                            logger.debug(f"Card error: {{exc}}")
                            continue
{pagination_loop_end}
            except Exception as exc:
                logger.error(f"Page error {{base_url}}: {{exc}}")
            finally:
                await page.close()

        await browser.close()

    logger.info(f"Scraped {{len(products)}} products from {site_name}")
    return products
