"""
Auto-generated by WebInspector
URL: {url}
Technology: {technology}  (jQuery / Static HTML)
Generated: {generated_date}

Selectors:
  Card:  {card_selector}  ({card_count} found on inspection)
  Name:  {name_selector}
  Price: {price_selector}
  Link:  {link_selector}

Pagination: {pagination_type}  (param: {pagination_param})

Note: Static/jQuery sites can usually be scraped without a full browser.
      This scraper uses requests + BeautifulSoup for efficiency.
      If the site loads content via AJAX, switch the scrape_page() implementation
      to the commented-out Playwright version.
"""
import logging
import re
import time
import requests
from bs4 import BeautifulSoup
from src.utils import parse_tr_price

logger = logging.getLogger("bakkal_monitor.parsers.{site_name}")

BASE_URL = "{base_url}"
TARGET_URLS = [{target_urls}]
CARD_SEL   = "{card_selector}"
NAME_SEL   = "{name_selector}"
PRICE_SEL  = "{price_selector}"
LINK_SEL   = "{link_selector}"
{pagination_const}

HEADERS = {{
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/120.0.0.0 Safari/537.36"
    ),
    "Accept-Language": "tr-TR,tr;q=0.9",
}}


def _extract_cards(soup: BeautifulSoup, base_url: str) -> list[dict]:
    """Extract products from a parsed page."""
    results = []
    cards = soup.select(CARD_SEL)
    for card in cards:
        try:
            name_el  = card.select_one(NAME_SEL)
            price_el = card.select_one(PRICE_SEL)
            if not name_el or not price_el:
                continue
            name      = name_el.get_text(strip=True)
            price_raw = price_el.get_text(strip=True)
            price     = parse_tr_price(price_raw)

            # Link extraction
            link_el = card.select_one(LINK_SEL) if LINK_SEL else None
            if not link_el:
                link_el = card.find_parent("a") or card.find("a")
            href = link_el.get("href", "") if link_el else ""
            if href and not href.startswith("http"):
                href = BASE_URL.rstrip("/") + "/" + href.lstrip("/")

            results.append({{
                "product_name":  name,
                "current_price": price,
                "market_name":   "{site_name}",
                "product_url":   href or base_url,
            }})
        except Exception as exc:
            logger.debug(f"Card error: {{exc}}")
    return results


def scrape_page(url: str) -> list[dict]:
    """Fetch and parse a single page (synchronous, no browser)."""
    try:
        resp = requests.get(url, headers=HEADERS, timeout=30)
        resp.raise_for_status()
        soup = BeautifulSoup(resp.text, "html.parser")
        return _extract_cards(soup, url)
    except Exception as exc:
        logger.error(f"Request error {{url}}: {{exc}}")
        return []


async def scrape() -> list[dict]:
    """Main scrape entry point (async wrapper for compatibility)."""
    import asyncio
    products: list[dict] = []

    for base_url in TARGET_URLS:
{pagination_loop_start_sync}
            cards = await asyncio.get_event_loop().run_in_executor(
                None, scrape_page, page_url
            )
            if not cards:
                logger.info(f"No cards — stopping at page {{page_num}}")
                break
            products.extend(cards)
            time.sleep(1.5)  # polite delay
{pagination_loop_end_sync}

    logger.info(f"Scraped {{len(products)}} products from {site_name}")
    return products
